const CURRENCY_ICON: Record<string, string> = {
  BLUR: "🟠",
  bNEO: "🟢",
  BUSD: "🪙",
  USD: "💵",
  ETH: "Ξ",
  GMX: "🔷",
  STEVMOS: "🔺",
  LUNA: "🌕",
  RATOM: "🟠",
  STRD: "🔵",
  EVMOS: "🟠",
  IBCX: "🌍",
  IRIS: "🌸",
  ampLUNA: "🌗",
  KUJI: "🟣",
  STOSMO: "🔷",
  USDC: "💲",
  axlUSDC: "💲",
  ATOM: "🔵",
  STATOM: "🔵",
  OSMO: "🟣",
  rSWTH: "🔴",
  STLUNA: "🌕",
  LSI: "💎",
  OKB: "🔵",
  OKT: "🔵",
  SWTH: "🔴",
  USC: "💵",
  WBTC: "₿",
  wstETH: "Ξ",
  YieldUSD: "💰",
  ZIL: "🟢",
};

export default CURRENCY_ICON;
